version: "3.4"

services:
  app:
    build: app
    image: app
    restart: "no"
    volumes:
      - ./app/:/app
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: database-0c6f3260-be9f-4b73-b010-aade961d0110
    image: postgres:14.1
    restart: "no"
    volumes:
      - ./data/:/data
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env